name: Qase Test Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Your build and setup steps here

      - name: Run Qase Tests
        uses: qase-tms/qase-cloud-ci-integrations@v1
        with:
          project_code: 'AI'
          api_token: ${{ secrets.QASE_API_TOKEN }}
          run_title: 'GitHub Actions Run'
          case_ids: '1'
        
