- name: Run Qase Tests
  uses: qase-tms/qase-cloud-ci-integrations/github@v1
  with:
    project_code: 'DEMO'
    api_token: ${{ secrets.QASE_API_TOKEN }}
    run_title: 'GitHub Actions Run'
    case_ids: '1'
