name: Run All Qase Tests

on:
  push:
    branches:
      - master 

jobs:
  run-qase-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run All Qase Tests
        uses: qase-tms/qase-cloud-ci-integrations/github@v1
        with:
          project_code: 'AI'
          api_token: ${{ secrets.QASE_API_TOKEN }}
          run_title: 'GitHub Actions Run'
          case_ids: '1'
          browser: 'chromium'
